# Generated by Django 2.2.6 on 2020-03-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200311_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'default_permissions': (), 'permissions': (('get_user', '查看用户'), ('add_user', '添加用户'), ('edit_user', '编辑用户'), ('del_user', '删除用户')), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
